# Generated by Django 4.2.1 on 2023-06-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataentries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.TextField(blank=True, null=True)),
                ('dataentry_id', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataentries',
                'managed': False,
            },
        ),
    ]
